# This is a basic workflow to help you get started with Actions

name: PowerShellGallery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push: 
    branches-ignore: ['master']
  pull_request:
    branches-ignore: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Runs some powershell
        shell: pwsh
        continue-on-error: true
        run: |
          Install-Module -Name BuildUtils -AllowPrerelease -RequiredVersion 0.4.0-alpha0025 -Scope CurrentUser -Force
          Import-Module BuildUtils
          $ci_engine = 'github'
          Write-LogError "This is the first error"
          Write-LogError -Message "This is second error then exit" -$haltExecution $true
          Write-LogError "This is the third error"
